
/**
 * Abstract:
 * axi_master_directed_sequence is used by test to provide initiator
 * scenario information to the Master agent present in the System Env.
 * This class defines a sequence in which a AXI WRITE followed by a AXI READ
 * sequence is generated by assigning values to the transactions rather than
 * randomization, and then transmitted using `uvm_send.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */

`ifndef GUARD_AXI_MASTER_DIRECTED_SEQUENCE_SV
`define GUARD_AXI_MASTER_DIRECTED_SEQUENCE_SV

class axi_master_directed_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  int bid;
  bit[39:0] waddr;
  bit[63:0] wdata;
  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         =  waddr;
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.burst_size   = svt_axi_transaction::BURST_SIZE_64BIT;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
      write_tran.burst_length = 1;




      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
        write_tran.data[i] = wdata;
      end
      foreach(write_tran.wstrb[i]) begin
        write_tran.wstrb[i] = 8'hff;
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=i;
      end

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);
      //bid=rsp.bid;
      //$display("bid %d",bid);
      `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_sequence











class axi_master_directed_write_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  int bid;
  bit[39:0] waddr;
  bit[63:0] wdata;
  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_write_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_write_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         =  waddr;
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.burst_size   = svt_axi_transaction::BURST_SIZE_32BIT;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
      write_tran.burst_length = 1;



      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
        write_tran.data[i] = wdata;
      end
      foreach(write_tran.wstrb[i]) begin
        write_tran.wstrb[i] = 8'hff;
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=i;
      end

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);
      //bid=rsp.bid;
      //$display("bid %d",bid);
      `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_write_sequence











class axi_master_directed_read_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  bit[39:0] raddr;
  bit[127:0] rdata;
  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_read_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_read_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

      for(int i = 0; i < sequence_length; i++) fork
      begin
      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.port_cfg     = cfg;
      read_tran.xact_type    = svt_axi_transaction::READ;
      read_tran.addr         = raddr;
      read_tran.burst_type   = svt_axi_transaction::INCR;
      read_tran.burst_size   = svt_axi_transaction::BURST_SIZE_32BIT;
      read_tran.atomic_type  = svt_axi_transaction::NORMAL;
      read_tran.burst_length = 1;

      read_tran.rresp        = new[read_tran.burst_length];
      read_tran.data         = new[read_tran.burst_length];
      read_tran.rready_delay = new[read_tran.burst_length];
      read_tran.data_user    = new[read_tran.burst_length];
      foreach (read_tran.rready_delay[i]) begin
        read_tran.rready_delay[i]=i;
      end

      /** Send the read transaction */
      `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
      rdata=rsp.data[0];
     read_tran.wait_for_transaction_end();
    `uvm_info("body", $sformatf("rdata=%d",rdata), UVM_LOW);


      `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
      end
    join

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_read_sequence





class axi_master_burst_write_sequence extends svt_axi_master_base_sequence;

    bit [39:0]  waddr;
    bit [63:0]  wdata[];
    bit [1:0]   bur_sel = 2'b01;
    bit [8:0]   bur_len = 4;
    bit [2:0]   wsize = 3'h3;

    bit delay_test;
    int avalid_delay_value;
    int aready_delay_value;
    int bvalid_delay_value;
    int bready_delay_value;
    int wvalid_delay_value[];
    int wready_delay_value[];

    rand int unsigned sequence_length = 1;

    constraint reasonable_sequence_length {
        sequence_length <= 100;
    }

    `uvm_object_utils(axi_master_burst_write_sequence)

    function new(string name="axi_master_burst_write_sequence");
        super.new(name);
    endfunction

    virtual task body();
        svt_axi_master_transaction write_tran, read_tran;
        svt_configuration get_cfg;
        bit status;

        super.body();

        status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
        `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

        p_sequencer.get_cfg(get_cfg);
        if (!$cast(cfg, get_cfg)) begin
            `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
        end

        for(int i = 0; i < sequence_length; i++) begin
            `uvm_create(write_tran)
            write_tran.port_cfg     = cfg;
            write_tran.xact_type    = svt_axi_transaction::WRITE;
            write_tran.addr         = waddr;
            if(bur_sel == 2'b00)
                write_tran.burst_type = svt_axi_transaction::FIXED;
            else if(bur_sel == 2'b01)
                write_tran.burst_type = svt_axi_transaction::INCR;
            else if(bur_sel == 2'b10)
                write_tran.burst_type = svt_axi_transaction::WRAP;
            else
                write_tran.burst_type = svt_axi_transaction::INCR;
            write_tran.burst_size   = wsize;
            write_tran.atomic_type  = svt_axi_transaction::NORMAL;
            if(bur_sel != 2'b10)
                write_tran.burst_length = bur_len;
            else
                write_tran.burst_length = 16;

            write_tran.data         = new[write_tran.burst_length];
            write_tran.wstrb        = new[write_tran.burst_length];
            write_tran.data_user    = new[write_tran.burst_length];
            foreach (write_tran.data[i]) begin
              write_tran.data[i] = wdata[i];
            end

            if (wsize == 3'b00)begin
                foreach(write_tran.wstrb[i]) begin
                    write_tran.wstrb[i] = 8'h01;
                end
            end
            else if (wsize == 3'b01)begin
                foreach(write_tran.wstrb[i]) begin
                    write_tran.wstrb[i] = 8'h03;
                end
            end
            else if (wsize == 3'b10)begin
                foreach(write_tran.wstrb[i]) begin
                    write_tran.wstrb[i] = 8'h0f;
                end
            end
            else begin
                foreach(write_tran.wstrb[i]) begin
                    write_tran.wstrb[i] = 8'hff;
                end
            end

            write_tran.addr_valid_delay = avalid_delay_value;
            write_tran.addr_ready_delay = aready_delay_value;
            write_tran.bvalid_delay     = bvalid_delay_value;
            write_tran.bready_delay     = bready_delay_value;
            write_tran.wvalid_delay     = new[write_tran.burst_length];
            write_tran.wready_delay     = new[write_tran.burst_length];
            foreach (write_tran.wvalid_delay[i]) begin
                if(delay_test == 1'b1) begin
                    write_tran.wvalid_delay[i] = wvalid_delay_value[i];
                    write_tran.wready_delay[i] = wready_delay_value[i];
                end
                else begin
                    write_tran.wvalid_delay[i] = 1;
                    write_tran.wready_delay[i] = 1;
                end
            end

            `uvm_send(write_tran)

            get_response(rsp);
            `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);
        end
    endtask: body

endclass: axi_master_burst_write_sequence




class axi_master_burst_read_sequence extends svt_axi_master_base_sequence;

    bit [39:0] raddr;
    bit [127:0] rdata[];
    bit [1:0]  bur_sel = 2'b01;
    bit [8:0]  bur_len = 4;
    bit [2:0]  rsize = 3'h3;

    bit delay_test;
    int avalid_delay_value;
    int aready_delay_value;
    int rvalid_delay_value[];
    int rready_delay_value[];

    rand int unsigned sequence_length = 1;

    constraint reasonable_sequence_length {
        sequence_length <= 100;
    }

    `uvm_object_utils(axi_master_burst_read_sequence)

    function new(string name="axi_master_burst_read_sequence");
        super.new(name);
    endfunction

    virtual task body();
        svt_axi_master_transaction write_tran, read_tran;
        svt_configuration get_cfg;
        bit status;
        `uvm_info("body", "Entered ...", UVM_LOW)

        super.body();

        status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
        `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

        p_sequencer.get_cfg(get_cfg);
        if (!$cast(cfg, get_cfg)) begin
            `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
        end

        for(int i = 0; i < sequence_length; i++) fork
            begin
                `uvm_create(read_tran)
                read_tran.port_cfg   = cfg;
                read_tran.xact_type  = svt_axi_transaction::READ;
                read_tran.addr       = raddr;
                if(bur_sel == 2'b00)
                    read_tran.burst_type = svt_axi_transaction::FIXED;
                else if(bur_sel == 2'b01)
                    read_tran.burst_type = svt_axi_transaction::INCR;
                else if(bur_sel == 2'b10)
                    read_tran.burst_type = svt_axi_transaction::WRAP;
                else
                    read_tran.burst_type = svt_axi_transaction::INCR;
                read_tran.burst_size   = rsize;
                read_tran.atomic_type  = svt_axi_transaction::NORMAL;
                if(bur_sel != 2'b10)
                    read_tran.burst_length = bur_len;
                else
                    read_tran.burst_length = 16;

                read_tran.rresp        = new[read_tran.burst_length];
                read_tran.data         = new[read_tran.burst_length];
                read_tran.data_user    = new[read_tran.burst_length];

                read_tran.addr_valid_delay = avalid_delay_value;
                read_tran.addr_ready_delay = aready_delay_value;
                read_tran.rvalid_delay     = new[read_tran.burst_length];
                read_tran.rready_delay     = new[read_tran.burst_length];
                foreach (read_tran.rready_delay[i]) begin
                    if(delay_test == 1'b1) begin
                        read_tran.rvalid_delay[i] = rvalid_delay_value[i];
                        read_tran.rready_delay[i] = rready_delay_value[i];
                    end
                    else begin
                        read_tran.rvalid_delay[i] = 1;
                        read_tran.rready_delay[i] = 1;
                    end
                end

                `uvm_send(read_tran)

                get_response(rsp);
                //rdata=rsp.data;
                read_tran.wait_for_transaction_end();
                `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
            end
        join
    endtask: body

endclass: axi_master_burst_read_sequence


class axi_master_directed_write_64b_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  int bid;
  bit[39:0] waddr;
  bit[63:0] wdata;
  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_write_64b_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_write_64b_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         =  waddr;
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.burst_size   = svt_axi_transaction::BURST_SIZE_64BIT;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
      write_tran.burst_length = 1;



      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
        write_tran.data[i] = wdata;
      end
      foreach(write_tran.wstrb[i]) begin
        write_tran.wstrb[i] = 8'hff;
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=i;
      end

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);
      //bid=rsp.bid;
      //$display("bid %d",bid);
      `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_write_64b_sequence











class axi_master_directed_read_64b_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  bit[39:0] raddr;
  bit[63:0] rdata;
  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_read_64b_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_read_64b_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

      for(int i = 0; i < sequence_length; i++) fork
      begin
      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.port_cfg     = cfg;
      read_tran.xact_type    = svt_axi_transaction::READ;
      read_tran.addr         = raddr;
      read_tran.burst_type   = svt_axi_transaction::INCR;
      read_tran.burst_size   = svt_axi_transaction::BURST_SIZE_64BIT;
      read_tran.atomic_type  = svt_axi_transaction::NORMAL;
      read_tran.burst_length = 1;

      read_tran.rresp        = new[read_tran.burst_length];
      read_tran.data         = new[read_tran.burst_length];
      read_tran.rready_delay = new[read_tran.burst_length];
      read_tran.data_user    = new[read_tran.burst_length];
      foreach (read_tran.rready_delay[i]) begin
        read_tran.rready_delay[i]=i;
      end

      /** Send the read transaction */
      `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
      rdata=rsp.data[0];
    `uvm_info("body", $sformatf("rdata=%d",rdata), UVM_LOW);
          read_tran.wait_for_transaction_end();

      `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
      end
    join

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_read_64b_sequence



class axi_master_directed_write_256B_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  int bid;
  bit[39:0] waddr;
  bit[127:0] wdata;
  bit[2:0]  wsize = 3'h3;
  /** Cnstrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_write_256B_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_write_256B_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         =  waddr;
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.burst_size   = wsize;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
      write_tran.burst_length = 1;



      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
        write_tran.data[i] = wdata;
      end
      if (wsize == 3'b00)begin
            foreach(write_tran.wstrb[i]) begin
                write_tran.wstrb[i] = 32'h01;
            end
      end
      else if (wsize == 3'b01)begin
            foreach(write_tran.wstrb[i]) begin
                write_tran.wstrb[i] = 32'h03;
            end
      end
      else if (wsize == 3'b10)begin
            foreach(write_tran.wstrb[i]) begin
                write_tran.wstrb[i] = 32'h0f;
            end
      end
      else if (wsize == 3'b11)begin
            foreach(write_tran.wstrb[i]) begin
                write_tran.wstrb[i] = 32'hff;
            end
      end
      else if (wsize == 3'b100)begin
            foreach(write_tran.wstrb[i]) begin
                write_tran.wstrb[i] = 32'hffff;
            end
      end
      else if (wsize == 3'b101)begin
            foreach(write_tran.wstrb[i]) begin
                write_tran.wstrb[i] = 32'hffffffff;
            end
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=i;
      end

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);
      //bid=rsp.bid;
      $display("bid %d",bid);
      `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_write_256B_sequence











class axi_master_directed_read_256B_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 1;
  bit[39:0] raddr;
  bit[127:0] rdata;
  bit[2:0]  rsize = 3'h3;
  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(axi_master_directed_read_256B_sequence)

  /** Class Constructor */
  function new(string name="axi_master_directed_read_256B_sequence");
    super.new(name);
  endfunction

  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

      for(int i = 0; i < sequence_length; i++) fork
      begin
      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.port_cfg     = cfg;
      read_tran.xact_type    = svt_axi_transaction::READ;
      read_tran.addr         = raddr;
      read_tran.burst_type   = svt_axi_transaction::INCR;
      read_tran.burst_size   = rsize;
      read_tran.atomic_type  = svt_axi_transaction::NORMAL;
      read_tran.burst_length = 1;

      read_tran.rresp        = new[read_tran.burst_length];
      read_tran.data         = new[read_tran.burst_length];
      read_tran.rready_delay = new[read_tran.burst_length];
      read_tran.data_user    = new[read_tran.burst_length];
      foreach (read_tran.rready_delay[i]) begin
        read_tran.rready_delay[i]=i;
      end

      /** Send the read transaction */
      `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
      rdata=rsp.data[0];
     read_tran.wait_for_transaction_end();
    `uvm_info("body", $sformatf("rdata=%d",rdata), UVM_LOW);


      `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
      end
    join

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: axi_master_directed_read_256B_sequence



class axi_master_burst_write_256B_sequence extends svt_axi_master_base_sequence;

    bit [39:0]  waddr;
    bit [127:0] wdata[];
    bit [1:0]   bur_sel = 2'b01;
    bit [8:0]   bur_len = 4;
    bit [2:0]   wsize = 3'h3;

    bit delay_test;
    int avalid_delay_value;
    int aready_delay_value;
    int bvalid_delay_value;
    int bready_delay_value;
    int wvalid_delay_value[];
    int wready_delay_value[];

    rand int unsigned sequence_length = 1;

    constraint reasonable_sequence_length {
        sequence_length <= 100;
    }

    `uvm_object_utils(axi_master_burst_write_256B_sequence)

    function new(string name="axi_master_burst_write_256B_sequence");
        super.new(name);
    endfunction

    virtual task body();
        svt_axi_master_transaction write_tran, read_tran;
        svt_configuration get_cfg;
        bit status;

        super.body();

        status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
        `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

        p_sequencer.get_cfg(get_cfg);
        if (!$cast(cfg, get_cfg)) begin
            `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
        end

        for(int i = 0; i < sequence_length; i++) begin
            `uvm_create(write_tran)
            write_tran.port_cfg     = cfg;
            write_tran.xact_type    = svt_axi_transaction::WRITE;
            write_tran.addr         = waddr;
            if(bur_sel == 2'b00)
                write_tran.burst_type = svt_axi_transaction::FIXED;
            else if(bur_sel == 2'b01)
                write_tran.burst_type = svt_axi_transaction::INCR;
            else if(bur_sel == 2'b10)
                write_tran.burst_type = svt_axi_transaction::WRAP;
            else
                write_tran.burst_type = svt_axi_transaction::INCR;
            write_tran.burst_size   = wsize;
            write_tran.atomic_type  = svt_axi_transaction::NORMAL;
            if(bur_sel != 2'b10)
                write_tran.burst_length = bur_len;
            else
                write_tran.burst_length = 16;

            write_tran.data         = new[write_tran.burst_length];
            write_tran.wstrb        = new[write_tran.burst_length];
            write_tran.data_user    = new[write_tran.burst_length];
            foreach (write_tran.data[i]) begin
              write_tran.data[i] = wdata[i];
            end
            if (wsize == 3'b00)begin
               foreach(write_tran.wstrb[i]) begin
                   write_tran.wstrb[i] = 32'h01;
               end
            end
            else if (wsize == 3'b01)begin
               foreach(write_tran.wstrb[i]) begin
                   write_tran.wstrb[i] = 32'h03;
               end
            end
            else if (wsize == 3'b10)begin
               foreach(write_tran.wstrb[i]) begin
                   write_tran.wstrb[i] = 32'h0f;
               end
            end
            else if (wsize == 3'b11)begin
               foreach(write_tran.wstrb[i]) begin
                   write_tran.wstrb[i] = 32'hff;
               end
            end
            else if (wsize == 3'b100)begin
               foreach(write_tran.wstrb[i]) begin
                   write_tran.wstrb[i] = 32'hffff;
               end
            end
            else if (wsize == 3'b101)begin
               foreach(write_tran.wstrb[i]) begin
                   write_tran.wstrb[i] = 32'hffffffff;
               end
            end


            write_tran.addr_valid_delay = avalid_delay_value;
            write_tran.addr_ready_delay = aready_delay_value;
            write_tran.bvalid_delay     = bvalid_delay_value;
            write_tran.bready_delay     = bready_delay_value;
            write_tran.wvalid_delay     = new[write_tran.burst_length];
            write_tran.wready_delay     = new[write_tran.burst_length];
            foreach (write_tran.wvalid_delay[i]) begin
                if(delay_test == 1'b1) begin
                    write_tran.wvalid_delay[i] = wvalid_delay_value[i];
                    write_tran.wready_delay[i] = wready_delay_value[i];
                end
                else begin
                    write_tran.wvalid_delay[i] = 1;
                    write_tran.wready_delay[i] = 1;
                end
            end

            `uvm_send(write_tran)

            get_response(rsp);
            `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);
        end
    endtask: body

endclass: axi_master_burst_write_256B_sequence



class axi_master_burst_read_256B_sequence extends svt_axi_master_base_sequence;

    bit [39:0] raddr;
    bit [127:0]rdata[];
    bit [1:0]  bur_sel = 2'b01;
    bit [8:0]  bur_len = 4;
    bit [2:0]  rsize = 3'h3;

    bit delay_test;
    int avalid_delay_value;
    int aready_delay_value;
    int rvalid_delay_value[];
    int rready_delay_value[];

    rand int unsigned sequence_length = 1;

    constraint reasonable_sequence_length {
        sequence_length <= 100;
    }

    `uvm_object_utils(axi_master_burst_read_256B_sequence)

    function new(string name="axi_master_burst_read_256B_sequence");
        super.new(name);
    endfunction

    virtual task body();
        svt_axi_master_transaction write_tran, read_tran;
        svt_configuration get_cfg;
        bit status;
        `uvm_info("body", "Entered ...", UVM_LOW)

        super.body();

        status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
        `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

        p_sequencer.get_cfg(get_cfg);
        if (!$cast(cfg, get_cfg)) begin
            `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
        end

        for(int i = 0; i < sequence_length; i++) fork
            begin
                `uvm_create(read_tran)
                read_tran.port_cfg   = cfg;
                read_tran.xact_type  = svt_axi_transaction::READ;
                read_tran.addr       = raddr;
                if(bur_sel == 2'b00)
                    read_tran.burst_type = svt_axi_transaction::FIXED;
                else if(bur_sel == 2'b01)
                    read_tran.burst_type = svt_axi_transaction::INCR;
                else if(bur_sel == 2'b10)
                    read_tran.burst_type = svt_axi_transaction::WRAP;
                else
                    read_tran.burst_type = svt_axi_transaction::INCR;
                read_tran.burst_size   = rsize;
                read_tran.atomic_type  = svt_axi_transaction::NORMAL;
                if(bur_sel != 2'b10)
                    read_tran.burst_length = bur_len;
                else
                    read_tran.burst_length = 16;

                read_tran.rresp        = new[read_tran.burst_length];
                read_tran.data         = new[read_tran.burst_length];
                read_tran.data_user    = new[read_tran.burst_length];

                read_tran.addr_valid_delay = avalid_delay_value;
                read_tran.addr_ready_delay = aready_delay_value;
                read_tran.rvalid_delay     = new[read_tran.burst_length];
                read_tran.rready_delay     = new[read_tran.burst_length];
                foreach (read_tran.rready_delay[i]) begin
                    if(delay_test == 1'b1) begin
                        read_tran.rvalid_delay[i] = rvalid_delay_value[i];
                        read_tran.rready_delay[i] = rready_delay_value[i];
                    end
                    else begin
                        read_tran.rvalid_delay[i] = 1;
                        read_tran.rready_delay[i] = 1;
                    end
                end

                `uvm_send(read_tran)

                get_response(rsp);
                //rdata=rsp.data;
                read_tran.wait_for_transaction_end();
                `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
            end
        join
    endtask: body

endclass: axi_master_burst_read_256B_sequence




`endif // GUARD_AXI_MASTER_DIRECTED_SEQUENCE_SV
