+incdir+/App/synopsys/vcs/T-2022.06-SP2/etc/uvm-1.2
+incdir+/library/techlib/vip/vip1/vip/svt/common/W-2024.09/sverilog/include
+incdir+/library/techlib/vip/vip1/vip/svt/amba_svt/W-2024.09/sverilog/include
+incdir+/library/techlib/vip/vip1/vip/svt/i2c_svt/W-2024.09/sverilog/include
+incdir+/library/techlib/vip/vip1/vip/svt/i2c_svt/W-2024.09/sverilog/src/vcs
+incdir+/library/techlib/vip/vip1/vip/svt/i2c_svt/W-2024.09/sverilog/src/com
+incdir+$ZC_NPU_VERIF_ROOT/2_verf/it/i2c_tb/env/vip/apb_vip/env
+incdir+$ZC_NPU_VERIF_ROOT/2_verf/it/i2c_tb/env/vip/axi_vip/env
+incdir+$ZC_NPU_VERIF_ROOT/2_verf/it/i2c_tb/env/vip/ahb_vip/env
+incdir+$ZC_NPU_VERIF_ROOT/2_verf/it/i2c_tb/env/vip/i2c_vip/env
+incdir+$ZC_NPU_VERIF_ROOT/2_verf/it/i2c_tb/env/vip

/App/synopsys/vcs/T-2022.06-SP2/etc/uvm-1.2/uvm_pkg.sv
/library/techlib/vip/vip1/vip/svt/common/W-2024.09/sverilog/include/svt.uvm.pkg
/library/techlib/vip/vip1/vip/svt/common/W-2024.09/sverilog/include/svt_mem.uvm.pkg
/library/techlib/vip/vip1/vip/svt/amba_svt/W-2024.09/sverilog/include/svt_axi.uvm.pkg
/library/techlib/vip/vip1/vip/svt/amba_svt/W-2024.09/sverilog/include/svt_ahb.uvm.pkg
/library/techlib/vip/vip1/vip/svt/amba_svt/W-2024.09/sverilog/include/svt_apb.uvm.pkg
/library/techlib/vip/vip1/vip/svt/i2c_svt/W-2024.09/sverilog/include/svt_i2c.uvm.pkg
