`ifndef CPU_INTR_CONNECTION_TEST_SV
`define CPU_INTR_CONNECTION_TEST_SV

class cpu_intr_connection_test extends chip_noc_base_test;
  `uvm_component_utils(cpu_intr_connection_test)

  extern function new(string name = "cpu_intr_connection_test", uvm_component parent = null);
  extern virtual task main_phase(uvm_phase phase);
  extern task test_intr_conn(string path, int index, string signal_name);
endclass

function cpu_intr_connection_test::new(string name = "cpu_intr_connection_test", uvm_component parent = null);
  super.new(name, parent);
endfunction : new

task cpu_intr_connection_test::main_phase(uvm_phase phase);
  super.main_phase(phase);
  phase.raise_objection(this);
  `uvm_info(get_type_name(), $psprintf("main_phase start!"), UVM_LOW)
  `uvm_info(get_type_name(), "cpu_intr_connection_test start", UVM_LOW);

  // TCU module tests
  test_intr_conn(`TCU_EVENT_Q_INTR_S_PATH, `TCU_EVENT_Q_INTR_S_IRQ_ID, "TCU_EVENT_Q_INTR_S");
  test_intr_conn(`TCU_EVENT_Q_INTR_NS_PATH, `TCU_EVENT_Q_INTR_NS_IRQ_ID, "TCU_EVENT_Q_INTR_NS");
  test_intr_conn(`TCU_PRI_Q_INTR_NS_PATH, `TCU_PRI_Q_INTR_NS_IRQ_ID, "TCU_PRI_Q_INTR_NS");
  test_intr_conn(`TCU_CMD_SYNC_INTR_NS_PATH, `TCU_CMD_SYNC_INTR_NS_IRQ_ID, "TCU_CMD_SYNC_INTR_NS");
  test_intr_conn(`TCU_CMD_SYNC_INTR_S_PATH, `TCU_CMD_SYNC_INTR_S_IRQ_ID, "TCU_CMD_SYNC_INTR_S");
  test_intr_conn(`TCU_GLOBAL_INTR_NS_PATH, `TCU_GLOBAL_INTR_NS_IRQ_ID, "TCU_GLOBAL_INTR_NS");
  test_intr_conn(`TCU_GLOBAL_INTR_S_PATH, `TCU_GLOBAL_INTR_S_IRQ_ID, "TCU_GLOBAL_INTR_S");
  test_intr_conn(`TCU_RAS_INTR_PATH, `TCU_RAS_INTR_IRQ_ID, "TCU_RAS_INTR");
  test_intr_conn(`TCU_PMU_INTR_PATH, `TCU_PMU_INTR_IRQ_ID, "TCU_PMU_INTR");

  // MCU GPIO tests
  test_intr_conn(`MCU_GPIO_INTR31_PATH, `MCU_GPIO_INTR31_IRQ_ID, "MCU_GPIO_INTR31");
  test_intr_conn(`MCU_GPIO_INTR30_PATH, `MCU_GPIO_INTR30_IRQ_ID, "MCU_GPIO_INTR30");
  test_intr_conn(`MCU_GPIO_INTR29_PATH, `MCU_GPIO_INTR29_IRQ_ID, "MCU_GPIO_INTR29");
  test_intr_conn(`MCU_GPIO_INTR28_PATH, `MCU_GPIO_INTR28_IRQ_ID, "MCU_GPIO_INTR28");
  test_intr_conn(`MCU_GPIO_INTR27_PATH, `MCU_GPIO_INTR27_IRQ_ID, "MCU_GPIO_INTR27");
  test_intr_conn(`MCU_GPIO_INTR26_PATH, `MCU_GPIO_INTR26_IRQ_ID, "MCU_GPIO_INTR26");
  test_intr_conn(`MCU_GPIO_INTR25_PATH, `MCU_GPIO_INTR25_IRQ_ID, "MCU_GPIO_INTR25");
  test_intr_conn(`MCU_GPIO_INTR24_PATH, `MCU_GPIO_INTR24_IRQ_ID, "MCU_GPIO_INTR24");
  test_intr_conn(`MCU_GPIO_INTR23_PATH, `MCU_GPIO_INTR23_IRQ_ID, "MCU_GPIO_INTR23");
  test_intr_conn(`MCU_GPIO_INTR22_PATH, `MCU_GPIO_INTR22_IRQ_ID, "MCU_GPIO_INTR22");
  test_intr_conn(`MCU_GPIO_INTR21_PATH, `MCU_GPIO_INTR21_IRQ_ID, "MCU_GPIO_INTR21");
  test_intr_conn(`MCU_GPIO_INTR20_PATH, `MCU_GPIO_INTR20_IRQ_ID, "MCU_GPIO_INTR20");
  test_intr_conn(`MCU_GPIO_INTR19_PATH, `MCU_GPIO_INTR19_IRQ_ID, "MCU_GPIO_INTR19");
  test_intr_conn(`MCU_GPIO_INTR18_PATH, `MCU_GPIO_INTR18_IRQ_ID, "MCU_GPIO_INTR18");
  test_intr_conn(`MCU_GPIO_INTR17_PATH, `MCU_GPIO_INTR17_IRQ_ID, "MCU_GPIO_INTR17");
  test_intr_conn(`MCU_GPIO_INTR16_PATH, `MCU_GPIO_INTR16_IRQ_ID, "MCU_GPIO_INTR16");
  test_intr_conn(`MCU_GPIO_INTR15_PATH, `MCU_GPIO_INTR15_IRQ_ID, "MCU_GPIO_INTR15");
  test_intr_conn(`MCU_GPIO_INTR14_PATH, `MCU_GPIO_INTR14_IRQ_ID, "MCU_GPIO_INTR14");
  test_intr_conn(`MCU_GPIO_INTR13_PATH, `MCU_GPIO_INTR13_IRQ_ID, "MCU_GPIO_INTR13");
  test_intr_conn(`MCU_GPIO_INTR12_PATH, `MCU_GPIO_INTR12_IRQ_ID, "MCU_GPIO_INTR12");
  test_intr_conn(`MCU_GPIO_INTR11_PATH, `MCU_GPIO_INTR11_IRQ_ID, "MCU_GPIO_INTR11");
  test_intr_conn(`MCU_GPIO_INTR10_PATH, `MCU_GPIO_INTR10_IRQ_ID, "MCU_GPIO_INTR10");
  test_intr_conn(`MCU_GPIO_INTR9_PATH, `MCU_GPIO_INTR9_IRQ_ID, "MCU_GPIO_INTR9");
  test_intr_conn(`MCU_GPIO_INTR8_PATH, `MCU_GPIO_INTR8_IRQ_ID, "MCU_GPIO_INTR8");
  test_intr_conn(`MCU_GPIO_INTR7_PATH, `MCU_GPIO_INTR7_IRQ_ID, "MCU_GPIO_INTR7");
  test_intr_conn(`MCU_GPIO_INTR6_PATH, `MCU_GPIO_INTR6_IRQ_ID, "MCU_GPIO_INTR6");
  test_intr_conn(`MCU_GPIO_INTR5_PATH, `MCU_GPIO_INTR5_IRQ_ID, "MCU_GPIO_INTR5");
  test_intr_conn(`MCU_GPIO_INTR4_PATH, `MCU_GPIO_INTR4_IRQ_ID, "MCU_GPIO_INTR4");
  test_intr_conn(`MCU_GPIO_INTR3_PATH, `MCU_GPIO_INTR3_IRQ_ID, "MCU_GPIO_INTR3");
  test_intr_conn(`MCU_GPIO_INTR2_PATH, `MCU_GPIO_INTR2_IRQ_ID, "MCU_GPIO_INTR2");
  test_intr_conn(`MCU_GPIO_INTR1_PATH, `MCU_GPIO_INTR1_IRQ_ID, "MCU_GPIO_INTR1");
  test_intr_conn(`MCU_GPIO_INTR0_PATH, `MCU_GPIO_INTR0_IRQ_ID, "MCU_GPIO_INTR0");

  // MCU MAILBOX tests
  test_intr_conn(`MCU_MAILBOX_INTR15_PATH, `MCU_MAILBOX_INTR15_IRQ_ID, "MCU_MAILBOX_INTR15");
  test_intr_conn(`MCU_MAILBOX_INTR14_PATH, `MCU_MAILBOX_INTR14_IRQ_ID, "MCU_MAILBOX_INTR14");
  test_intr_conn(`MCU_MAILBOX_INTR13_PATH, `MCU_MAILBOX_INTR13_IRQ_ID, "MCU_MAILBOX_INTR13");
  test_intr_conn(`MCU_MAILBOX_INTR12_PATH, `MCU_MAILBOX_INTR12_IRQ_ID, "MCU_MAILBOX_INTR12");
  test_intr_conn(`MCU_MAILBOX_INTR11_PATH, `MCU_MAILBOX_INTR11_IRQ_ID, "MCU_MAILBOX_INTR11");
  test_intr_conn(`MCU_MAILBOX_INTR10_PATH, `MCU_MAILBOX_INTR10_IRQ_ID, "MCU_MAILBOX_INTR10");
  test_intr_conn(`MCU_MAILBOX_INTR9_PATH, `MCU_MAILBOX_INTR9_IRQ_ID, "MCU_MAILBOX_INTR9");
  test_intr_conn(`MCU_MAILBOX_INTR8_PATH, `MCU_MAILBOX_INTR8_IRQ_ID, "MCU_MAILBOX_INTR8");
  test_intr_conn(`MCU_MAILBOX_INTR7_PATH, `MCU_MAILBOX_INTR7_IRQ_ID, "MCU_MAILBOX_INTR7");
  test_intr_conn(`MCU_MAILBOX_INTR6_PATH, `MCU_MAILBOX_INTR6_IRQ_ID, "MCU_MAILBOX_INTR6");
  test_intr_conn(`MCU_MAILBOX_INTR5_PATH, `MCU_MAILBOX_INTR5_IRQ_ID, "MCU_MAILBOX_INTR5");
  test_intr_conn(`MCU_MAILBOX_INTR4_PATH, `MCU_MAILBOX_INTR4_IRQ_ID, "MCU_MAILBOX_INTR4");
  test_intr_conn(`MCU_MAILBOX_INTR3_PATH, `MCU_MAILBOX_INTR3_IRQ_ID, "MCU_MAILBOX_INTR3");
  test_intr_conn(`MCU_MAILBOX_INTR2_PATH, `MCU_MAILBOX_INTR2_IRQ_ID, "MCU_MAILBOX_INTR2");
  test_intr_conn(`MCU_MAILBOX_INTR1_PATH, `MCU_MAILBOX_INTR1_IRQ_ID, "MCU_MAILBOX_INTR1");
  test_intr_conn(`MCU_MAILBOX_INTR0_PATH, `MCU_MAILBOX_INTR0_IRQ_ID, "MCU_MAILBOX_INTR0");

  // MCU DMA tests
  test_intr_conn(`MCU_DMA_CH7_INTR_PATH, `MCU_DMA_CH7_INTR_IRQ_ID, "MCU_DMA_CH7_INTR");
  test_intr_conn(`MCU_DMA_CH6_INTR_PATH, `MCU_DMA_CH6_INTR_IRQ_ID, "MCU_DMA_CH6_INTR");
  test_intr_conn(`MCU_DMA_CH5_INTR_PATH, `MCU_DMA_CH5_INTR_IRQ_ID, "MCU_DMA_CH5_INTR");
  test_intr_conn(`MCU_DMA_CH4_INTR_PATH, `MCU_DMA_CH4_INTR_IRQ_ID, "MCU_DMA_CH4_INTR");
  test_intr_conn(`MCU_DMA_CH3_INTR_PATH, `MCU_DMA_CH3_INTR_IRQ_ID, "MCU_DMA_CH3_INTR");
  test_intr_conn(`MCU_DMA_CH2_INTR_PATH, `MCU_DMA_CH2_INTR_IRQ_ID, "MCU_DMA_CH2_INTR");
  test_intr_conn(`MCU_DMA_CH1_INTR_PATH, `MCU_DMA_CH1_INTR_IRQ_ID, "MCU_DMA_CH1_INTR");
  test_intr_conn(`MCU_DMA_CH0_INTR_PATH, `MCU_DMA_CH0_INTR_IRQ_ID, "MCU_DMA_CH0_INTR");

  // MCU I2C/I3C/I2S tests
  test_intr_conn(`MCU_I2C3_INTR_PATH, `MCU_I2C3_INTR_IRQ_ID, "MCU_I2C3_INTR");
  test_intr_conn(`MCU_I2C2_INTR_PATH, `MCU_I2C2_INTR_IRQ_ID, "MCU_I2C2_INTR");
  test_intr_conn(`MCU_I2C1_INTR_PATH, `MCU_I2C1_INTR_IRQ_ID, "MCU_I2C1_INTR");
  test_intr_conn(`MCU_I2C0_INTR_PATH, `MCU_I2C0_INTR_IRQ_ID, "MCU_I2C0_INTR");
  test_intr_conn(`MCU_I3C1_INTR_PATH, `MCU_I3C1_INTR_IRQ_ID, "MCU_I3C1_INTR");
  test_intr_conn(`MCU_I3C0_INTR_PATH, `MCU_I3C0_INTR_IRQ_ID, "MCU_I3C0_INTR");
  test_intr_conn(`MCU_I2S1_INTR_PATH, `MCU_I2S1_INTR_IRQ_ID, "MCU_I2S1_INTR");
  test_intr_conn(`MCU_I2S0_INTR_PATH, `MCU_I2S0_INTR_IRQ_ID, "MCU_I2S0_INTR");

  // MCU SPI/XSPI tests
  test_intr_conn(`MCU_SPI1_INTR_PATH, `MCU_SPI1_INTR_IRQ_ID, "MCU_SPI1_INTR");
  test_intr_conn(`MCU_SPI0_INTR_PATH, `MCU_SPI0_INTR_IRQ_ID, "MCU_SPI0_INTR");
  test_intr_conn(`MCU_XSPI1_INTR_PATH, `MCU_XSPI1_INTR_IRQ_ID, "MCU_XSPI1_INTR");
  test_intr_conn(`MCU_XSPI0_INTR_PATH, `MCU_XSPI0_INTR_IRQ_ID, "MCU_XSPI0_INTR");

  // MCU UART/TIMER tests
  test_intr_conn(`MCU_UART3_INTR_PATH, `MCU_UART3_INTR_IRQ_ID, "MCU_UART3_INTR");
  test_intr_conn(`MCU_UART2_INTR_PATH, `MCU_UART2_INTR_IRQ_ID, "MCU_UART2_INTR");
  test_intr_conn(`MCU_UART1_INTR_PATH, `MCU_UART1_INTR_IRQ_ID, "MCU_UART1_INTR");
  test_intr_conn(`MCU_UART0_INTR_PATH, `MCU_UART0_INTR_IRQ_ID, "MCU_UART0_INTR");
  test_intr_conn(`MCU_TIMER1_INTR_PATH, `MCU_TIMER1_INTR_IRQ_ID, "MCU_TIMER1_INTR");
  test_intr_conn(`MCU_TIMER0_INTR_PATH, `MCU_TIMER0_INTR_IRQ_ID, "MCU_TIMER0_INTR");

  // MCU miscellaneous tests
  test_intr_conn(`MCU_CAN1_INTR_PATH, `MCU_CAN1_INTR_IRQ_ID, "MCU_CAN1_INTR");
  test_intr_conn(`MCU_CAN0_INTR_PATH, `MCU_CAN0_INTR_IRQ_ID, "MCU_CAN0_INTR");
  test_intr_conn(`MCU_ATB2AXI_INTR_PATH, `MCU_ATB2AXI_INTR_IRQ_ID, "MCU_ATB2AXI_INTR");
  test_intr_conn(`MCU_DMA_INTR_PATH, `MCU_DMA_INTR_IRQ_ID, "MCU_DMA_INTR");
  test_intr_conn(`MCU_NOC_INTR_PATH, `MCU_NOC_INTR_IRQ_ID, "MCU_NOC_INTR");
  test_intr_conn(`MCU_WDT_INTR_PATH, `MCU_WDT_INTR_IRQ_ID, "MCU_WDT_INTR");

  // HSM subsystem tests
  test_intr_conn(`HSM_MAILBOX_HOST_0_INTR_PATH, `HSM_MAILBOX_HOST_0_INTR_IRQ_ID, "HSM_MAILBOX_HOST_0_INTR");
  test_intr_conn(`HSM_MAILBOX_INTERNAL_INTR_PATH, `HSM_MAILBOX_INTERNAL_INTR_IRQ_ID, "HSM_MAILBOX_INTERNAL_INTR");
  test_intr_conn(`HSM_TRNG0_TRNG_INTR_PATH, `HSM_TRNG0_TRNG_INTR_IRQ_ID, "HSM_TRNG0_TRNG_INTR");
  test_intr_conn(`HSM_HASH0_INTR_PATH, `HSM_HASH0_INTR_IRQ_ID, "HSM_HASH0_INTR");
  test_intr_conn(`HSM_CRYP0_INTR_PATH, `HSM_CRYP0_INTR_IRQ_ID, "HSM_CRYP0_INTR");
  test_intr_conn(`HSM_ACRYP0_INTR_PATH, `HSM_ACRYP0_INTR_IRQ_ID, "HSM_ACRYP0_INTR");
  test_intr_conn(`HSM_RTC0_RTC_INTR_PATH, `HSM_RTC0_RTC_INTR_IRQ_ID, "HSM_RTC0_RTC_INTR");
  test_intr_conn(`HSM_BASIC_TIMER0_BSC_TIM_INTR_PATH, `HSM_BASIC_TIMER0_BSC_TIM_INTR_IRQ_ID, "HSM_BASIC_TIMER0_BSC_TIM_INTR");
  test_intr_conn(`HSM_USART0_UART_INTR_PATH, `HSM_USART0_UART_INTR_IRQ_ID, "HSM_USART0_UART_INTR");
  test_intr_conn(`HSM_UDMA0_UDMA_INTR_PATH, `HSM_UDMA0_UDMA_INTR_IRQ_ID, "HSM_UDMA0_UDMA_INTR");

  // UCIE tests
  test_intr_conn(`UCIE0_DBG_INTR_PATH, `UCIE0_DBG_INTR_IRQ_ID, "UCIE0_DBG_INTR");
  test_intr_conn(`UCIE0_MCU_DB2SOC_INTR_PATH, `UCIE0_MCU_DB2SOC_INTR_IRQ_ID, "UCIE0_MCU_DB2SOC_INTR");
  test_intr_conn(`UCIE1_DBG_INTR_PATH, `UCIE1_DBG_INTR_IRQ_ID, "UCIE1_DBG_INTR");
  test_intr_conn(`UCIE1_MCU_DB2SOC_INTR_PATH, `UCIE1_MCU_DB2SOC_INTR_IRQ_ID, "UCIE1_MCU_DB2SOC_INTR");

  // T2 UEE tests
  test_intr_conn(`T2_UEE_RAS_IRPT_PATH, `T2_UEE_RAS_IRPT_IRQ_ID, "T2_UEE_RAS_IRPT");
  test_intr_conn(`T2_UEE_PMU_IRPT_PATH, `T2_UEE_PMU_IRPT_IRQ_ID, "T2_UEE_PMU_IRPT");

  // AON GPIO tests
  test_intr_conn(`AON_GPIO_INTR31_PATH, `AON_GPIO_INTR31_IRQ_ID, "AON_GPIO_INTR31");
  test_intr_conn(`AON_GPIO_INTR30_PATH, `AON_GPIO_INTR30_IRQ_ID, "AON_GPIO_INTR30");
  test_intr_conn(`AON_GPIO_INTR29_PATH, `AON_GPIO_INTR29_IRQ_ID, "AON_GPIO_INTR29");
  test_intr_conn(`AON_GPIO_INTR28_PATH, `AON_GPIO_INTR28_IRQ_ID, "AON_GPIO_INTR28");
  test_intr_conn(`AON_GPIO_INTR27_PATH, `AON_GPIO_INTR27_IRQ_ID, "AON_GPIO_INTR27");
  test_intr_conn(`AON_GPIO_INTR26_PATH, `AON_GPIO_INTR26_IRQ_ID, "AON_GPIO_INTR26");
  test_intr_conn(`AON_GPIO_INTR25_PATH, `AON_GPIO_INTR25_IRQ_ID, "AON_GPIO_INTR25");
  test_intr_conn(`AON_GPIO_INTR24_PATH, `AON_GPIO_INTR24_IRQ_ID, "AON_GPIO_INTR24");
  test_intr_conn(`AON_GPIO_INTR23_PATH, `AON_GPIO_INTR23_IRQ_ID, "AON_GPIO_INTR23");
  test_intr_conn(`AON_GPIO_INTR22_PATH, `AON_GPIO_INTR22_IRQ_ID, "AON_GPIO_INTR22");
  test_intr_conn(`AON_GPIO_INTR21_PATH, `AON_GPIO_INTR21_IRQ_ID, "AON_GPIO_INTR21");
  test_intr_conn(`AON_GPIO_INTR20_PATH, `AON_GPIO_INTR20_IRQ_ID, "AON_GPIO_INTR20");
  test_intr_conn(`AON_GPIO_INTR19_PATH, `AON_GPIO_INTR19_IRQ_ID, "AON_GPIO_INTR19");
  test_intr_conn(`AON_GPIO_INTR18_PATH, `AON_GPIO_INTR18_IRQ_ID, "AON_GPIO_INTR18");
  test_intr_conn(`AON_GPIO_INTR17_PATH, `AON_GPIO_INTR17_IRQ_ID, "AON_GPIO_INTR17");
  test_intr_conn(`AON_GPIO_INTR16_PATH, `AON_GPIO_INTR16_IRQ_ID, "AON_GPIO_INTR16");
  test_intr_conn(`AON_GPIO_INTR15_PATH, `AON_GPIO_INTR15_IRQ_ID, "AON_GPIO_INTR15");
  test_intr_conn(`AON_GPIO_INTR14_PATH, `AON_GPIO_INTR14_IRQ_ID, "AON_GPIO_INTR14");
  test_intr_conn(`AON_GPIO_INTR13_PATH, `AON_GPIO_INTR13_IRQ_ID, "AON_GPIO_INTR13");
  test_intr_conn(`AON_GPIO_INTR12_PATH, `AON_GPIO_INTR12_IRQ_ID, "AON_GPIO_INTR12");
  test_intr_conn(`AON_GPIO_INTR11_PATH, `AON_GPIO_INTR11_IRQ_ID, "AON_GPIO_INTR11");
  test_intr_conn(`AON_GPIO_INTR10_PATH, `AON_GPIO_INTR10_IRQ_ID, "AON_GPIO_INTR10");
  test_intr_conn(`AON_GPIO_INTR9_PATH, `AON_GPIO_INTR9_IRQ_ID, "AON_GPIO_INTR9");
  test_intr_conn(`AON_GPIO_INTR8_PATH, `AON_GPIO_INTR8_IRQ_ID, "AON_GPIO_INTR8");
  test_intr_conn(`AON_GPIO_INTR7_PATH, `AON_GPIO_INTR7_IRQ_ID, "AON_GPIO_INTR7");
  test_intr_conn(`AON_GPIO_INTR6_PATH, `AON_GPIO_INTR6_IRQ_ID, "AON_GPIO_INTR6");
  test_intr_conn(`AON_GPIO_INTR5_PATH, `AON_GPIO_INTR5_IRQ_ID, "AON_GPIO_INTR5");
  test_intr_conn(`AON_GPIO_INTR4_PATH, `AON_GPIO_INTR4_IRQ_ID, "AON_GPIO_INTR4");
  test_intr_conn(`AON_GPIO_INTR3_PATH, `AON_GPIO_INTR3_IRQ_ID, "AON_GPIO_INTR3");
  test_intr_conn(`AON_GPIO_INTR2_PATH, `AON_GPIO_INTR2_IRQ_ID, "AON_GPIO_INTR2");
  test_intr_conn(`AON_GPIO_INTR1_PATH, `AON_GPIO_INTR1_IRQ_ID, "AON_GPIO_INTR1");
  test_intr_conn(`AON_GPIO_INTR0_PATH, `AON_GPIO_INTR0_IRQ_ID, "AON_GPIO_INTR0");

  // AON other tests
  test_intr_conn(`AON_CRG_INTR_PATH, `AON_CRG_INTR_IRQ_ID, "AON_CRG_INTR");
  test_intr_conn(`AON_PVTC_INTR_PATH, `AON_PVTC_INTR_IRQ_ID, "AON_PVTC_INTR");
  test_intr_conn(`AON_RTC_INTR_PATH, `AON_RTC_INTR_IRQ_ID, "AON_RTC_INTR");
  test_intr_conn(`AON_I2C0_INTR_PATH, `AON_I2C0_INTR_IRQ_ID, "AON_I2C0_INTR");
  test_intr_conn(`AON_I2C1_INTR_PATH, `AON_I2C1_INTR_IRQ_ID, "AON_I2C1_INTR");

  // TOP level tests
  test_intr_conn(`TOP_CRG_PLL_INTR_PATH, `TOP_CRG_PLL_INTR_IRQ_ID, "TOP_CRG_PLL_INTR");

  // DDR tests
  test_intr_conn(`LP0_DDR_INT_PATH, `LP0_DDR_INT_IRQ_ID, "LP0_DDR_INT");
  test_intr_conn(`LP1_DDR_INT_PATH, `LP1_DDR_INT_IRQ_ID, "LP1_DDR_INT");
  test_intr_conn(`LP2_DDR_INT_PATH, `LP2_DDR_INT_IRQ_ID, "LP2_DDR_INT");
  test_intr_conn(`LP3_DDR_INT_PATH, `LP3_DDR_INT_IRQ_ID, "LP3_DDR_INT");

  // HS DMA tests
  test_intr_conn(`HS_DMA_CH3_INTR_PATH, `HS_DMA_CH3_INTR_IRQ_ID, "HS_DMA_CH3_INTR");
  test_intr_conn(`HS_DMA_CH2_INTR_PATH, `HS_DMA_CH2_INTR_IRQ_ID, "HS_DMA_CH2_INTR");
  test_intr_conn(`HS_DMA_CH1_INTR_PATH, `HS_DMA_CH1_INTR_IRQ_ID, "HS_DMA_CH1_INTR");
  test_intr_conn(`HS_DMA_CH0_INTR_PATH, `HS_DMA_CH0_INTR_IRQ_ID, "HS_DMA_CH0_INTR");
  test_intr_conn(`HS_DMA_RAS_IRPT_PATH, `HS_DMA_RAS_IRPT_IRQ_ID, "HS_DMA_RAS_IRPT");
  test_intr_conn(`HS_DMA_PMU_IRPT_PATH, `HS_DMA_PMU_IRPT_IRQ_ID, "HS_DMA_PMU_IRPT");

  // HS USB tests
  test_intr_conn(`HS_USB_INTR1_PATH, `HS_USB_INTR1_IRQ_ID, "HS_USB_INTR1");
  test_intr_conn(`HS_USB_INTR0_PATH, `HS_USB_INTR0_IRQ_ID, "HS_USB_INTR0");
  test_intr_conn(`HS_USB_BCA_INTR_PATH, `HS_USB_BCA_INTR_IRQ_ID, "HS_USB_BCA_INTR");
  test_intr_conn(`HS_USB_HOST_SYS_ERR_INTR_PATH, `HS_USB_HOST_SYS_ERR_INTR_IRQ_ID, "HS_USB_HOST_SYS_ERR_INTR");

  // HS other tests
  test_intr_conn(`HS_EMMC_INTR_PATH, `HS_EMMC_INTR_IRQ_ID, "HS_EMMC_INTR");
  test_intr_conn(`HS_EMMC_WAKEUP_INTR_PATH, `HS_EMMC_WAKEUP_INTR_IRQ_ID, "HS_EMMC_WAKEUP_INTR");
  test_intr_conn(`HS_NVME_INTR_PATH, `HS_NVME_INTR_IRQ_ID, "HS_NVME_INTR");
  test_intr_conn(`HS_ETH_INTR_PATH, `HS_ETH_INTR_IRQ_ID, "HS_ETH_INTR");
  test_intr_conn(`HS_DATA_NOC_INTR_PATH, `HS_DATA_NOC_INTR_IRQ_ID, "HS_DATA_NOC_INTR");
  test_intr_conn(`HS_REG_NOC_INTR_PATH, `HS_REG_NOC_INTR_IRQ_ID, "HS_REG_NOC_INTR");
  test_intr_conn(`HS_HS_DMA_INTR_PATH, `HS_HS_DMA_INTR_IRQ_ID, "HS_HS_DMA_INTR");
  test_intr_conn(`SOC_NOC_INTR_PATH, `SOC_NOC_INTR_IRQ_ID, "SOC_NOC_INTR");

  // HS PCIe tests
  test_intr_conn(`HS_PCIESS01_PMU_IRPT_PATH, `HS_PCIESS01_PMU_IRPT_IRQ_ID, "HS_PCIESS01_PMU_IRPT");
  test_intr_conn(`HS_PCIESS01_RAS_IRPT_PATH, `HS_PCIESS01_RAS_IRPT_IRQ_ID, "HS_PCIESS01_RAS_IRPT");
  test_intr_conn(`HS_PCIESS01_MSI_INTR_PATH, `HS_PCIESS01_MSI_INTR_IRQ_ID, "HS_PCIESS01_MSI_INTR");
  test_intr_conn(`HS_PCIESS01_MSIDONE_INTR_PATH, `HS_PCIESS01_MSIDONE_INTR_IRQ_ID, "HS_PCIESS01_MSIDONE_INTR");
  test_intr_conn(`HS_PCIESS01_INTX_INTR_PATH, `HS_PCIESS01_INTX_INTR_IRQ_ID, "HS_PCIESS01_INTX_INTR");
  test_intr_conn(`HS_PCIESS01_STATUS_INTR_PATH, `HS_PCIESS01_STATUS_INTR_IRQ_ID, "HS_PCIESS01_STATUS_INTR");
  test_intr_conn(`HS_PCIESS01_ATU_INTR_PATH, `HS_PCIESS01_ATU_INTR_IRQ_ID, "HS_PCIESS01_ATU_INTR");
  test_intr_conn(`HS_PCIESS01_ERR_INTR_PATH, `HS_PCIESS01_ERR_INTR_IRQ_ID, "HS_PCIESS01_ERR_INTR");
  test_intr_conn(`HS_PCIESS01_DMA_INTR_PATH, `HS_PCIESS01_DMA_INTR_IRQ_ID, "HS_PCIESS01_DMA_INTR");
  test_intr_conn(`HS_PCIESS00_PMU_IRPT_PATH, `HS_PCIESS00_PMU_IRPT_IRQ_ID, "HS_PCIESS00_PMU_IRPT");
  test_intr_conn(`HS_PCIESS00_RAS_IRPT_PATH, `HS_PCIESS00_RAS_IRPT_IRQ_ID, "HS_PCIESS00_RAS_IRPT");
  test_intr_conn(`HS_PCIESS00_MSI_INTR_PATH, `HS_PCIESS00_MSI_INTR_IRQ_ID, "HS_PCIESS00_MSI_INTR");
  test_intr_conn(`HS_PCIESS00_MSIDONE_INTR_PATH, `HS_PCIESS00_MSIDONE_INTR_IRQ_ID, "HS_PCIESS00_MSIDONE_INTR");
  test_intr_conn(`HS_PCIESS00_INTX_INTR_PATH, `HS_PCIESS00_INTX_INTR_IRQ_ID, "HS_PCIESS00_INTX_INTR");
  test_intr_conn(`HS_PCIESS00_STATUS_INTR_PATH, `HS_PCIESS00_STATUS_INTR_IRQ_ID, "HS_PCIESS00_STATUS_INTR");
  test_intr_conn(`HS_PCIESS00_ATU_INTR_PATH, `HS_PCIESS00_ATU_INTR_IRQ_ID, "HS_PCIESS00_ATU_INTR");
  test_intr_conn(`HS_PCIESS00_ERR_INTR_PATH, `HS_PCIESS00_ERR_INTR_IRQ_ID, "HS_PCIESS00_ERR_INTR");
  test_intr_conn(`HS_PCIESS00_DMA_INTR_PATH, `HS_PCIESS00_DMA_INTR_IRQ_ID, "HS_PCIESS00_DMA_INTR");

  // MEDIA tests
  test_intr_conn(`MEDIA_SUB_GPU_SYSERR_INTR_PATH, `MEDIA_SUB_GPU_SYSERR_INTR_IRQ_ID, "MEDIA_SUB_GPU_SYSERR_INTR");
  test_intr_conn(`MEDIA_SUB_GPU_INTR_PATH, `MEDIA_SUB_GPU_INTR_IRQ_ID, "MEDIA_SUB_GPU_INTR");
  test_intr_conn(`MEDIA_SUB_DPU_INTR_PATH, `MEDIA_SUB_DPU_INTR_IRQ_ID, "MEDIA_SUB_DPU_INTR");
  test_intr_conn(`MEDIA_TBU_RAS_INTR_PATH, `MEDIA_TBU_RAS_INTR_IRQ_ID, "MEDIA_TBU_RAS_INTR");
  test_intr_conn(`MEDIA_TBU_PMU_INTR_PATH, `MEDIA_TBU_PMU_INTR_IRQ_ID, "MEDIA_TBU_PMU_INTR");
  test_intr_conn(`MEDIA_SUB_JPU_INTR_PATH, `MEDIA_SUB_JPU_INTR_IRQ_ID, "MEDIA_SUB_JPU_INTR");
  test_intr_conn(`MEDIA_SUB_VPU_INTR_0_PATH, `MEDIA_SUB_VPU_INTR_0_IRQ_ID, "MEDIA_SUB_VPU_INTR_0");
  test_intr_conn(`MEDIA_SUB_VPU_INTR_1_PATH, `MEDIA_SUB_VPU_INTR_1_IRQ_ID, "MEDIA_SUB_VPU_INTR_1");
  test_intr_conn(`MEDIA_SUB_VPU_INTR_2_PATH, `MEDIA_SUB_VPU_INTR_2_IRQ_ID, "MEDIA_SUB_VPU_INTR_2");
  test_intr_conn(`MEDIA_SUB_VPU_INTR_3_PATH, `MEDIA_SUB_VPU_INTR_3_IRQ_ID, "MEDIA_SUB_VPU_INTR_3");

  // Barrier and NPU tests
  test_intr_conn(`BARRIER_INTR_PATH, `BARRIER_INTR_IRQ_ID, "BARRIER_INTR");
  test_intr_conn(`NPU_INTR3_7_PATH, `NPU_INTR3_7_IRQ_ID, "NPU_INTR3_7");
  test_intr_conn(`NPU_INTR3_6_PATH, `NPU_INTR3_6_IRQ_ID, "NPU_INTR3_6");
  test_intr_conn(`NPU_INTR3_5_PATH, `NPU_INTR3_5_IRQ_ID, "NPU_INTR3_5");
  test_intr_conn(`NPU_INTR3_4_PATH, `NPU_INTR3_4_IRQ_ID, "NPU_INTR3_4");
  test_intr_conn(`NPU_INTR3_3_PATH, `NPU_INTR3_3_IRQ_ID, "NPU_INTR3_3");
  test_intr_conn(`NPU_INTR3_2_PATH, `NPU_INTR3_2_IRQ_ID, "NPU_INTR3_2");
  test_intr_conn(`NPU_INTR3_1_PATH, `NPU_INTR3_1_IRQ_ID, "NPU_INTR3_1");
  test_intr_conn(`NPU_INTR3_0_PATH, `NPU_INTR3_0_IRQ_ID, "NPU_INTR3_0");
  test_intr_conn(`NPU_INTR2_7_PATH, `NPU_INTR2_7_IRQ_ID, "NPU_INTR2_7");
  test_intr_conn(`NPU_INTR2_6_PATH, `NPU_INTR2_6_IRQ_ID, "NPU_INTR2_6");
  test_intr_conn(`NPU_INTR2_5_PATH, `NPU_INTR2_5_IRQ_ID, "NPU_INTR2_5");
  test_intr_conn(`NPU_INTR2_4_PATH, `NPU_INTR2_4_IRQ_ID, "NPU_INTR2_4");
  test_intr_conn(`NPU_INTR2_3_PATH, `NPU_INTR2_3_IRQ_ID, "NPU_INTR2_3");
  test_intr_conn(`NPU_INTR2_2_PATH, `NPU_INTR2_2_IRQ_ID, "NPU_INTR2_2");
  test_intr_conn(`NPU_INTR2_1_PATH, `NPU_INTR2_1_IRQ_ID, "NPU_INTR2_1");
  test_intr_conn(`NPU_INTR2_0_PATH, `NPU_INTR2_0_IRQ_ID, "NPU_INTR2_0");
  test_intr_conn(`NPU_INTR1_7_PATH, `NPU_INTR1_7_IRQ_ID, "NPU_INTR1_7");
  test_intr_conn(`NPU_INTR1_6_PATH, `NPU_INTR1_6_IRQ_ID, "NPU_INTR1_6");
  test_intr_conn(`NPU_INTR1_5_PATH, `NPU_INTR1_5_IRQ_ID, "NPU_INTR1_5");
  test_intr_conn(`NPU_INTR1_4_PATH, `NPU_INTR1_4_IRQ_ID, "NPU_INTR1_4");
  test_intr_conn(`NPU_INTR1_3_PATH, `NPU_INTR1_3_IRQ_ID, "NPU_INTR1_3");
  test_intr_conn(`NPU_INTR1_2_PATH, `NPU_INTR1_2_IRQ_ID, "NPU_INTR1_2");
  test_intr_conn(`NPU_INTR1_1_PATH, `NPU_INTR1_1_IRQ_ID, "NPU_INTR1_1");
  test_intr_conn(`NPU_INTR1_0_PATH, `NPU_INTR1_0_IRQ_ID, "NPU_INTR1_0");
  test_intr_conn(`NPU_INTR0_7_PATH, `NPU_INTR0_7_IRQ_ID, "NPU_INTR0_7");
  test_intr_conn(`NPU_INTR0_6_PATH, `NPU_INTR0_6_IRQ_ID, "NPU_INTR0_6");
  test_intr_conn(`NPU_INTR0_5_PATH, `NPU_INTR0_5_IRQ_ID, "NPU_INTR0_5");
  test_intr_conn(`NPU_INTR0_4_PATH, `NPU_INTR0_4_IRQ_ID, "NPU_INTR0_4");
  test_intr_conn(`NPU_INTR0_3_PATH, `NPU_INTR0_3_IRQ_ID, "NPU_INTR0_3");
  test_intr_conn(`NPU_INTR0_2_PATH, `NPU_INTR0_2_IRQ_ID, "NPU_INTR0_2");
  test_intr_conn(`NPU_INTR0_1_PATH, `NPU_INTR0_1_IRQ_ID, "NPU_INTR0_1");
  test_intr_conn(`NPU_INTR0_0_PATH, `NPU_INTR0_0_IRQ_ID, "NPU_INTR0_0");
  test_intr_conn(`NPU_WDT_INTR3_PATH, `NPU_WDT_INTR3_IRQ_ID, "NPU_WDT_INTR3");
  test_intr_conn(`NPU_WDT_INTR2_PATH, `NPU_WDT_INTR2_IRQ_ID, "NPU_WDT_INTR2");
  test_intr_conn(`NPU_WDT_INTR1_PATH, `NPU_WDT_INTR1_IRQ_ID, "NPU_WDT_INTR1");
  test_intr_conn(`NPU_WDT_INTR0_PATH, `NPU_WDT_INTR0_IRQ_ID, "NPU_WDT_INTR0");

  `uvm_info(get_type_name(), $psprintf("main_phase done!"), UVM_LOW)
  phase.drop_objection(this);
endtask : main_phase

task cpu_intr_connection_test::test_intr_conn(string path, int index, string signal_name);
  logic intr_value;
  string full_path;
  uvm_hdl_force(path, 1'b1);
  #80ns; // Wait for some time
  full_path = $sformatf("%s[%0d]", `INTR_SYNC_OUT_PATH, index);
  uvm_hdl_read(full_path, intr_value);
  if (intr_value) begin
    `uvm_info(get_type_name(), $psprintf("%s received at intr_sync_out[%0d]", signal_name, index), UVM_LOW);
  end else begin
    `uvm_error(get_type_name(), $psprintf("%s not received at intr_sync_out[%0d]", signal_name, index));
  end
  uvm_hdl_release(path);
endtask : test_intr_conn

`endif