
/**
 * Abstract:
 * apb_master_directed_sequence is used by test to provide initiator
 * scenario information to the Master agent present in the System Env.
 * This class defines a sequence in which a APB WRITE followed by a APB READ
 * sequence is generated by assigning values to the transactions rather than
 * randomization, and then transmitted using `uvm_send.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */

`ifndef GUARD_APB_MASTER_DIRECTED_SEQUENCE_SV
`define GUARD_APB_MASTER_DIRECTED_SEQUENCE_SV

class apb_master_directed_sequence extends svt_apb_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(apb_master_directed_sequence)

  /** Class Constructor */
  function new(string name="apb_master_directed_sequence");
    super.new(name);
  endfunction
 
  	
  
  virtual task body();
    svt_apb_master_transaction write_tran, read_tran;
    bit status;
    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", "Entered ...", UVM_LOW)
    end

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);
    end






    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.cfg       = cfg;
      write_tran.xact_type = svt_apb_transaction::WRITE;
      write_tran.address   = 32'h0000_0100 | ('h100 * i);
      write_tran.data      = i;
      write_tran.num_wait_cycles = 3;

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);

      if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
        `uvm_info("body", "APB WRITE transaction completed", UVM_LOW);
      end

      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.cfg       = cfg;
      read_tran.xact_type = svt_apb_transaction::READ;
      read_tran.address   = 32'h0000_0100 | ('h100 * i);

      /** Send the read transaction */
      `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
    
      if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
        `uvm_info("body", "APB READ transaction completed", UVM_LOW);
      end
    end

    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", "Exiting...", UVM_LOW)
    end
  endtask: body

endclass: apb_master_directed_sequence
















class apb_master_directed_write_sequence extends svt_apb_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(apb_master_directed_write_sequence)

  /** Class Constructor */
  function new(string name="apb_master_directed_write_sequence");
    super.new(name);
  endfunction
 
  rand bit[31:0] apb_w_data,apb_r_data,apb_w_addr,apb_r_addr ;

  
  virtual task body();
    svt_apb_master_transaction write_tran, read_tran;
    bit status;
    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", "Entered ...", UVM_LOW)
    end

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);
    end


	 //$display(cfg);
  
      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.cfg       = cfg;
      write_tran.xact_type = svt_apb_transaction::WRITE;
      write_tran.address   = apb_w_addr;
      write_tran.data      = apb_w_data;
      write_tran.num_wait_cycles = 3;

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);

      if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
        `uvm_info("body", "APB WRITE transaction completed", UVM_LOW);
      end




    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", "Exiting...", UVM_LOW)
    end
  endtask: body

endclass: apb_master_directed_write_sequence









class apb_master_directed_read_sequence extends svt_apb_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(apb_master_directed_read_sequence)

  /** Class Constructor */
  function new(string name="apb_master_directed_read_sequence");
    super.new(name);
  endfunction
 
  int apb_w_data,apb_r_data,apb_w_addr,apb_r_addr ;

  
  virtual task body();
    svt_apb_master_transaction write_tran, read_tran;
    bit status;
    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", "Entered ...", UVM_LOW)
    end

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);
    end



      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.cfg       = cfg;
      read_tran.xact_type = svt_apb_transaction::READ;
      read_tran.address   = apb_r_addr;

      /** Send the read transaction */
      `uvm_send(read_tran)
      /** Wait for the read transaction to complete */
      get_response(rsp);
  	  apb_r_data=rsp.data;  
      if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
        `uvm_info("body", "APB READ transaction completed", UVM_LOW);
      end


  



    if ($test$plusargs("APB_DIRECTED_VERBOSE")) begin
      `uvm_info("body", "Exiting...", UVM_LOW)
    end
  endtask: body

endclass: apb_master_directed_read_sequence





`endif // GUARD_APB_MASTER_DIRECTED_SEQUENCE_SV
